# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'
  imageName: 'stocksbot:$(Build.BuildId)'

steps:
- script: |
    dotnet restore ./StocksBot.sln
    dotnet build --configuration $(buildConfiguration) ./StocksBot.sln
    dotnet test StocksBot.UnitTests --configuration $(buildConfiguration) --logger trx
    dotnet publish ./StocksBot.sln --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

- script: |
    docker-compose build 
    docker tag stocksbot $(dockerId).azurecr.io/$(imageName)
    docker login -u $(dockerId) -p $(pswd) $(dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)