# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'
  imageName: 'stocksbot:$(Build.BuildId)'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'StocksBot.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'StocksBot.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'StocksBot.UnitTests'
    publishTestResults: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'StocksBot.sln'

- task: PublishBuildArtifacts@1

- task: DockerCompose@0
  inputs:
    action: 'build'

- task: Docker@1
  inputs:
    command: 'login'
    azureSubscription: 'davidmarek_registry'
    azureContainerRegistry: $(dockerId)

- task: Docker@1
  inputs:
    command: 'push'
    imageName: '$(dockerId).azurecr.io/$(imageName)'