# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'
  imageName: 'stocksbot:$(Build.BuildId)'

steps:

- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore'
  inputs:
    command: 'restore'
    projects: 'StocksBot.sln'

- task: DotNetCoreCLI@2
  displayName: DotNet Build
  inputs:
    command: 'build'
    projects: 'StocksBot.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: DotNet Test
  inputs:
    command: 'test'
    projects: 'StocksBot.UnitTests'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: DotNet Publish
  inputs:
    command: 'publish'
    projects: 'StocksBot.sln'
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1

- task: DockerCompose@0
  displayName: DockerCompose Build
  inputs:
    action: 'Build Services'
    dockerComposeFile: 'docker-compose.yml'
    workingDirectory: $(Build.SourcesDirectory)

- task: Docker@1
  displayName: Docker Login
  inputs:
    command: 'login'
    azureSubscription: 'davidmarek_registry'
    azureContainerRegistry: $(dockerId)

- task: Docker@1
  displayName: Docker Push
  inputs:
    command: 'push'
    imageName: '$(dockerId).azurecr.io/$(imageName)'