# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'stocksbot'
  azureSubscriptionEndpoint: 'davidmarek_azure_resource_manager'
  azureContainerRegistry: '{"loginServer":"davidmarek.azurecr.io", "id": "/subscriptions/330947ab-4149-4b63-979d-62af7a6f101a/resourceGroups/davidmarek/providers/Microsoft.ContainerRegistry/registries/davidmarek"}'

steps:

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.203'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore'
  inputs:
    command: 'restore'
    projects: 'StocksBot.sln'

- task: DotNetCoreCLI@2
  displayName: DotNet Build
  inputs:
    command: 'build'
    projects: 'StocksBot.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: DotNet Test
  inputs:
    command: 'test'
    projects: 'StocksBot.UnitTests'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: DotNet Publish
  inputs:
    command: 'publish'
    projects: 'StocksBot.sln'
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1

- task: DockerCompose@0
  displayName: DockerCompose Build
  inputs:
    action: 'Build services'
    containerregistrytype: 'Azure Container Registry'
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: 'docker-compose.yml'
    projectName: $(imageName)
    workingDirectory: $(Build.SourcesDirectory)
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildName)

- task: DockerCompose@0
  displayName: DockerCompose Push
  inputs:
    action: 'Push services'
    containerregistrytype: 'Azure Container Registry'
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    projectName: $(imageName)
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildName)
 