# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore ./StocksBot.sln
  displayName: Restore Dependencies
- script: dotnet build --configuration $(buildConfiguration) ./StocksBot.sln
  displayName: 'Build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--logger trx --collect "Code coverage"'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'