# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pr:
  - master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'stocksbot:$(Build.BuildNumber)'

steps:

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.203'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore'
  inputs:
    command: 'restore'
    projects: 'StocksBot.sln'

- task: DotNetCoreCLI@2
  displayName: DotNet Build
  inputs:
    command: 'build'
    projects: 'StocksBot.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: DotNet Test
  inputs:
    command: 'test'
    projects: 'StocksBot.UnitTests'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration)'