version: '3.4'

services:
  stocksbot:
    image: davidmarek.azurecr.io/stocksbot
    depends_on:
      - redis
    build:
      context: .
      dockerfile: StocksBot/Dockerfile
  redis:
    image: redis